# NumPy Module 
- .arrange()
- .array()
- .reshape()
- .shape
- mathematical operations on np arrays

In [2]:
import numpy as np

a = np.arange(6)
print(a,'\n')

b = np.array([1,2])
print(b,'\n')

c = np.array([[3],[4]])
print(c,'\n')

print("b+c is \n", b+c,'\n')
print("c+b is \n", c+b,'\n')
print("c+a is \n", a+c, '\n')
print("a+c is \n", c+a, '\n')

[0 1 2 3 4 5] 

[1 2] 

[[3]
 [4]] 

b+c is 
 [[4 5]
 [5 6]] 

c+b is 
 [[4 5]
 [5 6]] 

c+a is 
 [[3 4 5 6 7 8]
 [4 5 6 7 8 9]] 

a+c is 
 [[3 4 5 6 7 8]
 [4 5 6 7 8 9]] 



In [ ]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.shape) #prints dimensions of the array
print(a.size) #total number of elements of the array
print(a.ndim) #no. of axis of dimensions in the array
print(a.dtype) #type of every element 
print(a.itemsize, "\n") #size of bytes of every element in the array

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(type(b)) #ndarray as an array class of numpy

In [ ]:
a = np.arange(12).reshape(3,4)
print(a,"\n")
print(a.sum(axis=1),"\n") #sum in each row
print(a.sum(axis=0),"\n") #sum in each column 

c = np.array([[2.5,2.2,4.0],[9.1,5.6,7.3]])
print(c,"\n")
print(np.zeros((3,3)),"\n")
print(np.ones((2,3,4),dtype=np.int16),"\n") #two elements of (3,4) matrix

In [ ]:
import random 

print(np.arange(4,40,4)) #40 is not reached
print(np.arange(40,4,-4)) #4 is not reached
print(np.arange(1,3,0.5))

a = np.arange(10)
print("a = ",a)
print("square of a = ",a**2)
print(a>5)

b = np.random.random((3,4))
print("\n",b)
print(b.sum())
print(b.min())
print(b.max())

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
flat = arr.flatten()
print(flat,'\n')

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
check = b>3
print(check)
result = b[check]
print(result)

In [ ]:
print(b+1)
print(b-2)
print(b*10)
print(b**2)
print(b.T)
b *= 2
print(b)

# TicTacToe
- create a 3x3 board using numpy

In [8]:
import numpy as np

board = np.array([['-']*3]*3)
board = np.array(['-']*9).reshape((3,3))
play = "x"
playX = True
player1 = [0]*8
player2 = [0]*8
num_plays = 9

def check_win():
    if 3 in player1: return 1
    if -3 in player2: return -1
    else: return 0

def add_scores(score, row, col, point):
    score[row] += point #row point
    score[3 + col] += point #col point
    if row == col: score[6] += point #diagonal1
    if (2-col) == row: score[7] += point #diagonal2

def print_board():
    for row in board:
        print("{} {} {}".format(row[0],row[1],row[2]))

while num_plays != 0:
    num_plays -= 1
    print_board()

    i = int(input("Enter row position of "+play+": "))
    j = int(input("Enter column position of "+play+": "))

    while(True):
        if (i>0 and j>0) and (i<4 and j<4) and (board[i-1][j-1] == '-'): 
            board[i-1][j-1] = play
            break
        else: print("Invalid row and column")

    if playX: #player 1 - add +1's
        add_scores(player1, i-1, j-1, 1)
        playX = False
        play = "o"
    else: #player 2
        add_scores(player2, i-1, j-1, -1)
        playX = True
        play = "x"

    winner = check_win()
    if winner != 0:
        if winner == 1: print("Player 1 has won!")
        elif winner == 2: print("Player 2 has won!")
        print_board()
        break
        
if num_plays == 0: 
    print("It's a draw!")
    print_board()

- - -
- - -
- - -
Enter row position of x: 2
Enter column position of x: 2
- - -
- x -
- - -
Enter row position of o: 1
Enter column position of o: 1
o - -
- x -
- - -
Enter row position of x: 1
Enter column position of x: 2
o x -
- x -
- - -
Enter row position of o: 3
Enter column position of o: 2
o x -
- x -
- o -
Enter row position of x: 3
Enter column position of x: 1
o x -
- x -
x o -
Enter row position of o: 3
Enter column position of o: 3
o x -
- x -
x o o
Enter row position of x: 1
Enter column position of x: 3
Player 1 has won!
o x x
- x -
x o o
