In [5]:
path = "C:\\Users\\Michelle\\Documents\\Cummins\\Sem6\\JOCPython\\2020-4-14_docs\\"

## Flipping an Image 
We use the Pillow or PIL module in python to flip the image <br>
Directions that we can transpose the image are:
- PIL.Image.FLIP_LEFT_RIGHT : mirror image from left to right 
- PIL.Image.FLIP_TOP_BOTTOM : mirror image upside down
- PIL.Image.ROTATE_90 : rotate 90 deg anticlockwise
- PIL.Image.ROTATE_180 : rotate 180 deg anticlockwise - same as FLIP_LEFT_RIGHT then FLIP_TOP_BOTTOM
- PIL.Image.ROTATE_270 : rotate 270 anticlockwise 
- PIL.Image.TRANSPOSE : same as FLIP_LEFT_RIGHT then ROTATE_90

In [35]:
from PIL import Image
my_img = Image.open(path+"original2.png")
transposed_img = my_img.transpose(Image.FLIP_LEFT_RIGHT)
#there is no FLIP_RIGHT_LEFT - which would technically also have worked
transposed_img.save(path+"flipped2.png")

## Image Histogram 
What we will cover: 
- CLAHE Contrast Limited Adaptive Histogram Equalization
- How to flip the image - two ways

**Image Histogram**<br>
Type of histogram that acts as a graphical representation of the tonal distribution in a digital image. plots the number of pixels for each tonal value. You can judge the entire tonal distribution at a glance. <br>
Horizontal axis - tonal variations, Vertial axis - number of pixels. The left side of the horizontal axis represents the dark areas, middle represents the mid-tone values, and the right hand side represents the light areas.<br>
If a dark image, most of the data points will be on the left side. A bright image will have few dark areas and shadows will have most of its data points on the right side and center of the graph. <br>

**Histogram equalization**<br>
Trying to operate on the image so that the tonal values / contrast of the image is equally distributed in the histogram. <br>
Problem: if there is a small area then histogram equalization may work but if you have a large area then (high contrast) you might have a problem. <br>
Thats how *adaptive equalization* came about. The picture is divided into tiles and histogram equalization is applied to each tile. One method of adaptive histogram equalization is CLAHE.  

In [6]:
import cv2
#read the image - read as an image object
img = cv2.imread(path+"blur1.png")
#print the shape of the matrix row col channel (colours-3=RGB,0=Gray)
print("Colour image-blue1.png: Its shape is ",img.shape,"\n")
#print the numpy matrix of the image
print("Image matrix of colour image is",img,"\n")

Colour image-blue1.png: Its shape is  (531, 1890, 3) 

Image matrix of colour image is [[[27 28 10]
  [27 28 10]
  [26 26 10]
  ...
  [35 34 11]
  [35 34 11]
  [35 34 11]]

 [[27 28 10]
  [27 28 10]
  [27 28 10]
  ...
  [35 34 11]
  [35 34 11]
  [32 30 11]]

 [[27 28 10]
  [26 26 10]
  [26 26 10]
  ...
  [35 34 11]
  [35 34 11]
  [32 33  9]]

 ...

 [[31 35 15]
  [31 35 15]
  [33 39 15]
  ...
  [35 37 10]
  [33 39 15]
  [33 39 15]]

 [[31 35 15]
  [33 39 15]
  [33 39 15]
  ...
  [35 37 11]
  [33 36 11]
  [33 36 11]]

 [[31 35 15]
  [33 39 15]
  [31 34 15]
  ...
  [33 36 11]
  [33 36 11]
  [33 36 11]]] 



cv2.cvtColor(src, code[, dst[, dstCn]])<br>
- src: input image: 8-bit unsigned, 16-bit unsigned ( CV_16UC... ), or single-precision floating-point.
- dst: output image of the same size and depth as src

- code: color space conversion code (see the description below)
    - CV_BGR2GRAY, CV_RGB2GRAY, CV_GRAY2BGR, CV_GRAY2RGB 
    - difference between CV_BGR2GRAY and CV_RGB2GRAY: It's to do with how the colors are stored. The default pixel format of OpenCV is BGR so the first byte in a standard (24-bit) color image will be an 8-bit Blue component, the second byte will be Green, and the third byte will be Red. The opposite will be for RGB 
    - use GBR whenever needed. Only if you have obtained your image in a different format, used RGB
    
- dstCn: number of channels in the destination image; if the parameter is 0, the number of the channels is derived automatically from src and code


In [11]:
#creat a clahe method 
clahe = cv2.createCLAHE()
#for this method we need to convert the coloured image to grayscale
#we use cvtColor()
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#saved the converted gray image
cv2.imwrite(path+"blur1_gray.png",gray_img)

#a gray image does not print the channel/color code in shape: only row and coloumn is displayed
print("converted gray image of blur1.png's shape: ",gray_img.shape,"\n")
print("Image matrix of converted gray image-blur1.png is",gray_img,"\n")

#enhance the image on the gray image
enh_img = clahe.apply(gray_img)
cv2.imwrite(path+"blur1_gray_en.png",enh_img)

#enh_color_img = clahe.apply(img) - gives an error when you try to apply clahe to a colored image

converted gray image of blur1.png's shape:  (531, 1890) 

Image matrix of converted gray image-blur1.png is [[23 23 21 ... 27 27 27]
 [23 23 23 ... 27 27 25]
 [23 21 21 ... 27 27 26]
 ...
 [29 29 31 ... 29 31 31]
 [29 31 31 ... 29 28 28]
 [29 31 28 ... 28 28 28]] 



True

Are there any methods with which we can enhance a coloured image?<br>
PIL ImageEnhance module (https://pillow.readthedocs.io/en/3.0.x/reference/ImageEnhance.html)<br>
There are 4 classes : Contrast, Color, Brightness, Sharpness classes

**Brightness class** <br>
ImageEnhance.Brightness.enhance(factor)<br>
factor of 0.0 gives a black image, factor of 1.0 gives back the original image, as you increase the factor the image tends to white. At which factor the image would turn white would depend on the original brightness in the image. For blur1.png, it is somewhere between 25 and 30. 

In [46]:
from PIL import Image, ImageEnhance
img = Image.open(path+"blur1.png")
#create object of Brightness class
im_b = ImageEnhance.Brightness(img)
#enhance the image by a factor of 2.0
img_enhance = im_b.enhance(2.0)
img_enhance.save(path+"blur1_enh_pil.png")

**Contrast class** <br>
ImageEnhance.Contrast.enhance(factor)<br>
This class can be used to control the contrast of an image, similar to the contrast control on a TV set. Increase the brightness in the bright parts and decrease it in the dark parts. An enhancement factor of 0.0 gives a solid grey image. A factor of 1.0 gives the original image.

In [51]:
im_c = ImageEnhance.Contrast(img).enhance(2.0)
im_c.save(path+"blur1_contrast_pil.png")

**Color class** (Saturation)<br>
ImageEnhance.Color.enhance(factor)<br>
Adjust image color balance.
This class can be used to adjust the colour balance of an image, in a manner similar to the controls on a colour TV set. An enhancement factor of 0.0 gives a black and white image. A factor of 1.0 gives the original image.

In [55]:
im_col = ImageEnhance.Color(img).enhance(3.0)
im_col.save(path+"blur1_col_pil.png")

**Sharpness class** <br>
ImageEnhance.Sharpness.enhance(factor)<br>
Adjust image sharpness.
This class can be used to adjust the sharpness of an image. An enhancement factor of 0.0 gives a blurred image, a factor of 1.0 gives the original image. Increasing the factor increases the sharpness of the image.

In [62]:
im_s = ImageEnhance.Sharpness(img).enhance(10.0)
im_s.save(path+"blur1_sharp_pil.png")

im.show(img) will open the file in the default image viewer and on closing the window will save the image to the file system. 